### ISSUE TITLE
L2:Max Updater add support for old interface

### ISSUE THREAD

**Issue by phantom2005** [phantom2005/L2Max#5]
We want to give players the option to play with the old L2 Interlude interface.
The updater will get a new setting to change from the new interface to old.

**Comment by dougpauline02** [comment]
thank you, there is an issue I just ran into today, I am doing the quest for cleric, and have followed everything correctly, but; however, it is stuck to where it wants me to to Lionel, which I have  (image attached 
![quest](https://user-images.githubusercontent.com/58061935/115479633-b0cdb080-a1fd-11eb-8eb5-c3ef793c4df3.jpg)

**Comment by RescueMiner** [comment]
I want retail interface ! :((

**Comment by phantom2005** [comment]
> 
> 
> thank you, there is an issue I just ran into today, I am doing the quest for cleric, and have followed everything correctly, but; however, it is stuck to where it wants me to to Lionel, which I have (image attached) Can you help me plix plox? thank you
> ![quest](https://user-images.githubusercontent.com/58061935/115479633-b0cdb080-a1fd-11eb-8eb5-c3ef793c4df3.jpg)

This issue was resolved when we upgraded the files. Going to add the old interface to our updater.

**Comment by phantom2005** [comment]
Added to updater
![unknown](https://user-images.githubusercontent.com/21281799/116903401-aa4b2a00-ac3c-11eb-824a-8ae9f70c1d06.png)
